version: '3.5'
services:
  remix_app:
    container_name: remix-app
    build: .
    image: remix-app-img:latest
    ports:
      - "22114:3000"
    restart: always
    volumes:
      - ./:/usr/src/app
    environment:
      - AIRTABLE_KEY=keyzbjKNgu52lb9D3
